In [1]:
import numpy as np

OPENCV中cv.getRotationMatrix2D()中的angle,正值为逆时针，负值为顺时针

In [12]:
def rotate_image(image, angle):
    import cv2 as cv2
    h,w=image.shape[:2]
    center = w//2,h//2
    M = cv2.getRotationMatrix2D(center,-angle,1.0)
    return cv2.warpAffine(image,M,(h,w))

In [13]:
def main():
    # 5x5 的灰度图像
    image = np.array([[100, 150, 200, 50, 75],
                      [80, 120, 160, 40, 60],
                      [180, 210, 240, 90, 110],
                      [20, 30, 40, 10, 15],
                      [130, 170, 220, 70, 95]], dtype=np.uint8)
    # 旋转 90 度
    rotated_image = rotate_image(image, 90)
    print(rotated_image)

if __name__ == '__main__':
    main()

[[130  20 180  80 100]
 [170  30 210 120 150]
 [220  40 240 160 200]
 [ 70  10  90  40  50]
 [ 95  15 110  60  75]]
